# Site settings
title: Yeahia Sarker
description: Welcome to my world!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yeahia Sarker
user_description: Director of machine learning @anchorblock.vc focusing on machine learning and blockchain-based product. Experience in building scalable machine learning software systems leveraging state-of-the-art models. Proficient in handling large scale vision and language models.
user_title: Director @anchroblock.vc
email: yeahia@anchorblock.vc
twitter_username: yeahiasarker1
github_username:  yeahiasarker
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
